# Generated by Django 2.1.5 on 2019-02-12 14:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_things', models.CharField(max_length=64)),
                ('amount', models.IntegerField()),
                ('city', models.CharField(max_length=64)),
                ('street', models.CharField(max_length=64)),
                ('postal_code', models.CharField(max_length=5)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Numer musi być w formacie: '+999999999'. Do 15 cyfr.", regex='^\\+?1?\\d{9,15}$')])),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('extra_info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserExtended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64)),
                ('street', models.CharField(max_length=64)),
                ('postal_code', models.CharField(max_length=5)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Numer musi być w formacie: '+999999999'. Do 15 cyfr.", regex='^\\+?1?\\d{9,15}$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='type_of',
            field=models.ManyToManyField(to='main.TypeOf'),
        ),
        migrations.AddField(
            model_name='donation',
            name='type_of',
            field=models.ManyToManyField(to='main.TypeOf'),
        ),
    ]
